export const brand={name:"BCC Buildtech Limited",phone:"0124-6571500",email:"info@bcc-buildtech.com",address:"Unit No. 1146–1148, 11th Floor, JMD Megapolis, Sohna Road, Sector 48, Gurugram, Haryana 122018",linkedin:"https://in.linkedin.com/company/bcc-buildtech-gurugram-haryana"};
export const navigation=[
{label:"Company",href:"/about",children:[["About BCC","/about"],["Leadership","/leadership"],["Vision 2031","/vision-2031"]]},
{label:"Businesses",href:"/businesses",children:[["EPC","/epc"],["HAM","/ham"],["Roads & Highways","/businesses#roads"],["Bridges & Structures","/businesses#structures"]]},
{label:"Projects",href:"/projects",children:[["Project portfolio","/projects"],["Market presence","/projects#presence"],["Featured credentials","/projects#featured"]]},
{label:"Capabilities",href:"/capabilities",children:[["Plant & machinery","/capabilities#machinery"],["People","/capabilities#people"],["Quality & safety","/quality-safety-sustainability"]]},
{label:"Impact",href:"/csr",children:[["CSR","/csr"],["Sustainability","/quality-safety-sustainability"],["Media centre","/media"]]}];
export const projects=[
{id:"akegwo-avangkhu",state:"Nagaland",title:"Akegwo–Avangkhu Section of NH-202K, Package III",authority:"NHIDCL",model:"EPC",segment:"Highways",status:"Ongoing",progress:35,value:"₹272.59 Cr",length:"36.941 km",image:"/bcc/project-nagaland.jpg",summary:"Widening to two lanes with hard shoulders from design chainage 69+875 km to 106+816 km under NH(O)-NE."},
{id:"narmadapuram-timarni",state:"Madhya Pradesh",title:"Narmadapuram–Timarni Road",authority:"MPRDC",model:"HAM",segment:"Highways",status:"Ongoing",progress:20,value:"₹380.00 Cr",length:"Package scope",image:"/bcc/hero-asphalt.jpg",summary:"Upgradation and reconstruction from intermediate lane to two lanes with paved shoulders, excluding specified ROB and flyover works."},
{id:"maram-peren",state:"Manipur",title:"Maram–Peren Section, NH-129A Package III",authority:"NHIDCL",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹269.42 Cr",length:"34.494 km",image:"/bcc/project-manipur.jpg",summary:"Improvement of the existing road to two lanes with hard shoulders from km 75+000 to km 109+494."},
{id:"nh40-meghalaya",state:"Meghalaya",title:"NH-40 / NH-44 Improvement, Package I",authority:"NHIDCL",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹166.06 Cr",length:"11.600 km",image:"/bcc/project-meghalaya.jpg",summary:"Two-lane paved-shoulder and four-lane improvement works delivered under JICA Loan Assistance as balance works."},
{id:"nilokheri-karsa-dhand",state:"Haryana",title:"Nilokheri–Karsa–Dhand Road",authority:"PWD B&R Haryana",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹24.98 Cr",length:"24.64 km",image:"/bcc/hero-asphalt.jpg",summary:"Four-laning and widening/strengthening works in Karnal district under the CRF scheme."},
{id:"kalanaur-kail",state:"Haryana",title:"Kalanaur–Kail Four-Lane Road",authority:"PWD B&R Haryana",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹24.43 Cr",length:"23.132 km",image:"/bcc/hero-asphalt.jpg",summary:"Four-lane road works through the city portion of Yamuna Nagar district."},
{id:"nh72-himachal",state:"Himachal Pradesh",title:"NH-72 Kala Amb–Paonta Sahib–Dehradun Road",authority:"NH Himachal Pradesh",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹22.18 Cr",length:"7 km package",image:"/bcc/project-nagaland.jpg",summary:"DBM, BC, road furniture, drainage, median, retaining wall, footpath and utility-shifting works."},
{id:"karnal-munak",state:"Haryana",title:"Karnal–Munak Road",authority:"PWD B&R Haryana",model:"EPC",segment:"Highways",status:"Completed",progress:100,value:"₹21.06 Cr",length:"16.48 km",image:"/bcc/hero-asphalt.jpg",summary:"Widening and strengthening with dense bituminous macadam and bituminous concrete in Karnal district."},
{id:"kesri-bihta-rob",state:"Haryana",title:"Kesri–Bihta Road ROB/LHS",authority:"PWD B&R Haryana",model:"EPC",segment:"Structures",status:"Completed",progress:100,value:"₹19.58 Cr",length:"Level crossing 117",image:"/bcc/project-meghalaya.jpg",summary:"Construction of ROB/LHS in lieu of Level Crossing No. 117 on the Saharanpur–Ambala section."}];
export const machinery=[
["Hot Mix Plant - Batch Type","Apollo ANP 1500","Asphalt",1],["Hot Mix Plant - Drum Type","Apollo & KDI","Asphalt",3],["Motor Grader","Komatsu","Earthwork",5],["Soil Compactor","HAMM / Wirtgen","Compaction",5],["Backhoe Excavator","JCB / CAT","Earthwork",7],["Milling Machine","Wirtgen","Pavement",1],["Front End Loader","JCB","Materials",5],["Excavator","Volvo, CAT & Kobelco","Earthwork",42],["Pneumatic Tyre Roller","Volvo","Compaction",1],["Tandem Vibratory Roller","Volvo","Compaction",3],["Sensor Paver Finisher","Apollo & Vögele","Pavement",2],["Mechanical Paver","Apollo","Pavement",1],["Baby Roller","Case & JCB","Compaction",2],["Static Roller","Kalsi","Compaction",7],["Weighbridge","LEO","Controls",4],["Dumper","TATA","Logistics",43],["Self-Loading Mixer","Schwing Stetter","Concrete",6],["RMC Batching Plant","Schwing Stetter / Apollo / Venus","Concrete",5],["Mobile Stone Crusher","Etrack & Terex, 350 TPH","Materials",2],["Stone Cone Crusher","Metso, 100 TPH","Materials",1],["Concrete Pump","Schwing Stetter","Concrete",3],["Air Compressor","ELGI","Plant",5],["DG Set","Cummins, CAT & Kirloskar","Plant",7],["Water Tanker","Various","Logistics",4],["Sand Screen Plant","Local","Materials",2],["WMM Plant","KDI","Pavement",2],["Transit Mixer","TATA","Concrete",7],["Boom Placer","Schwing Stetter","Concrete",2],["Tractor with Trolley","New Holland, Ford & Mahindra","Logistics",6],["Rock Drill Machine","Epiroc","Structures",3]] as const;
export const financials={fy23:90.50,fy24:190.93,fy25:265.97,h1fy26:165,orderBook:867,netWorth:59.67,ebitda25:55.12,pat25:33.71,ebitdaMargin25:20.72,patMargin25:12.63,gearing25:0.42,interestCoverage25:11.96};
export const rating={longTerm:"IVR BBB+ / Stable",shortTerm:"IVR A2",facilities:"₹110 Cr",date:"31 December 2025"};
export const leadership=[
{name:"Mr. Bhoop Singh",role:"Managing Director",experience:"20+ years",qualification:"Civil engineering background",image:"/bcc/bhoop-singh.jpg"},
{name:"Mr. Ashok Lamba",role:"Sr. Vice President - Projects",experience:"45 years",qualification:"BSc Engineering (Civil)"},
{name:"Mr. Vijay Kumar",role:"Chief Financial Officer",experience:"39 years",qualification:"MBA"},
{name:"Mr. Surender Kumar Chaudhary",role:"Vice President - Technical",experience:"34 years",qualification:"BE Civil"},
{name:"Mr. Rajindra Singh",role:"General Manager - Plant & Machinery",experience:"24 years",qualification:"Production Engineering"},
{name:"Mr. Kunal Sood",role:"Project Manager",experience:"18 years",qualification:"B.Tech Civil"}];
const vids=["https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4","https://videos.pexels.com/video-files/3255275/3255275-hd_1920_1080_25fps.mp4","https://videos.pexels.com/video-files/2053100/2053100-hd_1920_1080_25fps.mp4","https://videos.pexels.com/video-files/4488706/4488706-hd_1920_1080_25fps.mp4"];
const imgs=["https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=2200&q=88","https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=2200&q=88","https://images.unsplash.com/photo-1473445361085-b9a07f55608b?auto=format&fit=crop&w=2200&q=88","https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=2200&q=88"];
export const pageMeta:Record<string,{eyebrow:string;title:string;copy:string;image:string;video:string}>={
about:{eyebrow:"ABOUT BCC",title:"Two decades of infrastructure execution.",copy:"Established in 2003 as Bharat Construction Company and reconstituted as BCC Buildtech Limited, the enterprise delivers roads, highways, buildings and structures for public-sector clients.",image:"/bcc/project-nagaland.jpg",video:vids[0]},
leadership:{eyebrow:"LEADERSHIP",title:"Experience that moves projects forward.",copy:"Execution-driven management aligned across delivery, commercial discipline, quality, safety and stakeholder trust.",image:imgs[1],video:vids[1]},
businesses:{eyebrow:"OUR BUSINESSES",title:"Built for EPC. Ready for HAM.",copy:"Integrated capability across highways, bridges, structures and complex road-development programmes.",image:imgs[2],video:vids[2]},
epc:{eyebrow:"EPC EXPERTISE",title:"One accountable execution platform.",copy:"Engineering coordination, procurement, mobilisation, construction, quality control and delivery—managed as one programme.",image:imgs[3],video:vids[3]},
ham:{eyebrow:"HAM CAPABILITY",title:"Built for long-term asset performance.",copy:"A disciplined approach to Hybrid Annuity Model evaluation, execution, contractual governance and maintenance readiness.",image:imgs[2],video:vids[2]},
projects:{eyebrow:"PROJECTS",title:"Infrastructure measured by impact.",copy:"Explore nine disclosed credentials across Nagaland, Madhya Pradesh, Manipur, Meghalaya, Haryana and Himachal Pradesh.",image:"/bcc/project-meghalaya.jpg",video:vids[3]},
capabilities:{eyebrow:"EXECUTION CAPABILITY",title:"The strength behind every milestone.",copy:"Experienced management, a disclosed fleet of 187 machines and equipment units, and specialised project teams aligned for execution at scale.",image:"/bcc/machinery-plant.jpg",video:vids[0]},
"quality-safety-sustainability":{eyebrow:"QHSE",title:"Execution without compromise.",copy:"Quality assurance, safety discipline and responsible construction embedded across the project lifecycle.",image:imgs[3],video:vids[3]},
csr:{eyebrow:"CSR",title:"Progress beyond infrastructure.",copy:"A structured platform for community development, education, skills, environment and worker welfare.",image:"https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=2200&q=88",video:vids[1]},
media:{eyebrow:"MEDIA CENTRE",title:"Progress, documented.",copy:"Project milestones, engineering stories, leadership perspectives and responsible corporate communication.",image:imgs[2],video:vids[2]},
careers:{eyebrow:"CAREERS",title:"Build infrastructure. Build your career.",copy:"Opportunities for engineers, project professionals and field teams shaping Indian connectivity.",image:imgs[1],video:vids[1]},
contact:{eyebrow:"CONTACT",title:"Let’s build the next connection.",copy:"Business, partnership, vendor, career and media enquiries through our Gurugram head office.",image:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=2200&q=88",video:vids[1]},
"vision-2031":{eyebrow:"VISION 2031",title:"Scaling with discipline.",copy:"A five-pillar roadmap for capability, geographic reach, governance and sustainable growth.",image:imgs[2],video:vids[2]}};
